import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LateralMenu from "@/components/generalComponents/LateralMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">     
      <body className={inter.className}>
        <main className="flex">
          <section className="h-[100vh] bg-blue-800">
            <LateralMenu/>
          </section>
          <section className="h-[100vh] w-[100%] bg-blue-100">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
